import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // ── Focus Achievements ─────────────────────────────────────────────────────
  {
    id: 'first_focus',
    title: 'First Spark',
    description: 'Complete your very first focus session.',
    emoji: '⚡',
    category: 'focus',
    xpReward: 50,
    requirement: { type: 'focus_minutes', value: 1 },
  },
  {
    id: 'focus_1h',
    title: 'Deep Diver',
    description: 'Accumulate 60 minutes of total focus time.',
    emoji: '🌊',
    category: 'focus',
    xpReward: 100,
    requirement: { type: 'focus_minutes', value: 60 },
  },
  {
    id: 'focus_5h',
    title: 'Flow Architect',
    description: 'Reach 5 hours of total focused work.',
    emoji: '🏛️',
    category: 'focus',
    xpReward: 250,
    requirement: { type: 'focus_minutes', value: 300 },
  },
  {
    id: 'focus_10h',
    title: 'Time Bender',
    description: 'Master 10 hours of deep focus.',
    emoji: '⏱️',
    category: 'focus',
    xpReward: 500,
    requirement: { type: 'focus_minutes', value: 600 },
  },
  {
    id: 'focus_50h',
    title: 'NeuroPilot Elite',
    description: '50 hours of focused productivity. Legendary.',
    emoji: '🚀',
    category: 'focus',
    xpReward: 2000,
    requirement: { type: 'focus_minutes', value: 3000 },
  },

  // ── Task Achievements ──────────────────────────────────────────────────────
  {
    id: 'first_task',
    title: 'Task Starter',
    description: 'Complete your first task. Every journey begins here.',
    emoji: '✅',
    category: 'tasks',
    xpReward: 30,
    requirement: { type: 'task_count', value: 1 },
  },
  {
    id: 'tasks_10',
    title: 'Momentum Builder',
    description: 'Complete 10 tasks.',
    emoji: '🎯',
    category: 'tasks',
    xpReward: 100,
    requirement: { type: 'task_count', value: 10 },
  },
  {
    id: 'tasks_50',
    title: 'Execution Machine',
    description: 'Complete 50 tasks. You mean business.',
    emoji: '⚙️',
    category: 'tasks',
    xpReward: 400,
    requirement: { type: 'task_count', value: 50 },
  },
  {
    id: 'tasks_100',
    title: 'Century Club',
    description: '100 tasks completed. Absolutely unstoppable.',
    emoji: '💯',
    category: 'tasks',
    xpReward: 1000,
    requirement: { type: 'task_count', value: 100 },
  },

  // ── Habit Achievements ─────────────────────────────────────────────────────
  {
    id: 'habit_3day',
    title: 'Seed Planted',
    description: 'Maintain a 3-day habit streak.',
    emoji: '🌱',
    category: 'habits',
    xpReward: 60,
    requirement: { type: 'habit_streak', value: 3 },
  },
  {
    id: 'habit_7day',
    title: 'Week Warrior',
    description: 'Complete a full week habit streak.',
    emoji: '🔥',
    category: 'habits',
    xpReward: 150,
    requirement: { type: 'habit_streak', value: 7 },
  },
  {
    id: 'habit_21day',
    title: 'Neural Rewired',
    description: '21 consecutive days — habit formation confirmed.',
    emoji: '🧠',
    category: 'habits',
    xpReward: 500,
    requirement: { type: 'habit_streak', value: 21 },
  },
  {
    id: 'habit_30day',
    title: 'Iron Discipline',
    description: '30-day habit streak. You are different now.',
    emoji: '🏆',
    category: 'habits',
    xpReward: 1000,
    requirement: { type: 'habit_streak', value: 30 },
  },
  {
    id: 'habit_66day',
    title: 'Automaticity',
    description: "66 days — the science says it's automatic now.",
    emoji: '✨',
    category: 'habits',
    xpReward: 3000,
    requirement: { type: 'habit_streak', value: 66 },
  },

  // ── Streak Achievements ────────────────────────────────────────────────────
  {
    id: 'streak_3',
    title: 'Getting Started',
    description: 'Use NeuroPilot 3 days in a row.',
    emoji: '📅',
    category: 'streak',
    xpReward: 50,
    requirement: { type: 'habit_streak', value: 3 },
  },
  {
    id: 'streak_7',
    title: 'Consistent',
    description: 'A full week of showing up.',
    emoji: '🗓️',
    category: 'streak',
    xpReward: 150,
    requirement: { type: 'habit_streak', value: 7 },
  },

  // ── Level Milestones ───────────────────────────────────────────────────────
  {
    id: 'level_5',
    title: 'Rising Pilot',
    description: 'Reach Level 5.',
    emoji: '🛫',
    category: 'milestone',
    xpReward: 200,
    requirement: { type: 'level', value: 5 },
  },
  {
    id: 'level_10',
    title: 'Co-Pilot',
    description: 'Reach Level 10. Your brain and NeuroPilot are in sync.',
    emoji: '✈️',
    category: 'milestone',
    xpReward: 500,
    requirement: { type: 'level', value: 10 },
  },
  {
    id: 'level_20',
    title: 'Senior Navigator',
    description: "Level 20 — you've mastered the system.",
    emoji: '🌟',
    category: 'milestone',
    xpReward: 1500,
    requirement: { type: 'level', value: 20 },
  },
  {
    id: 'level_50',
    title: 'Neuro Legend',
    description: 'Level 50. You are the NeuroPilot.',
    emoji: '👑',
    category: 'milestone',
    xpReward: 5000,
    requirement: { type: 'level', value: 50 },
    secret: true,
  },
];

export const ACHIEVEMENT_MAP = Object.fromEntries(ACHIEVEMENTS.map((a) => [a.id, a])) as Record<
  string,
  Achievement
>;
